// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: opencog.proto

#include "opencog.pb.h"
#include "opencog.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace opencogservices {

static const char* ServiceDefinition_method_names[] = {
  "/opencogservices.ServiceDefinition/execute",
};

std::unique_ptr< ServiceDefinition::Stub> ServiceDefinition::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ServiceDefinition::Stub> stub(new ServiceDefinition::Stub(channel));
  return stub;
}

ServiceDefinition::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_execute_(ServiceDefinition_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ServiceDefinition::Stub::execute(::grpc::ClientContext* context, const ::opencogservices::Command& request, ::opencogservices::CommandOutput* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_execute_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::opencogservices::CommandOutput>* ServiceDefinition::Stub::AsyncexecuteRaw(::grpc::ClientContext* context, const ::opencogservices::Command& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::opencogservices::CommandOutput>::Create(channel_.get(), cq, rpcmethod_execute_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::opencogservices::CommandOutput>* ServiceDefinition::Stub::PrepareAsyncexecuteRaw(::grpc::ClientContext* context, const ::opencogservices::Command& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::opencogservices::CommandOutput>::Create(channel_.get(), cq, rpcmethod_execute_, context, request, false);
}

ServiceDefinition::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServiceDefinition_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ServiceDefinition::Service, ::opencogservices::Command, ::opencogservices::CommandOutput>(
          std::mem_fn(&ServiceDefinition::Service::execute), this)));
}

ServiceDefinition::Service::~Service() {
}

::grpc::Status ServiceDefinition::Service::execute(::grpc::ServerContext* context, const ::opencogservices::Command* request, ::opencogservices::CommandOutput* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace opencogservices

