// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: opencog.proto
#ifndef GRPC_opencog_2eproto__INCLUDED
#define GRPC_opencog_2eproto__INCLUDED

#include "opencog.pb.h"

#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace opencogservices {

class ServiceDefinition final {
 public:
  static constexpr char const* service_full_name() {
    return "opencogservices.ServiceDefinition";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status execute(::grpc::ClientContext* context, const ::opencogservices::Command& request, ::opencogservices::CommandOutput* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::opencogservices::CommandOutput>> Asyncexecute(::grpc::ClientContext* context, const ::opencogservices::Command& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::opencogservices::CommandOutput>>(AsyncexecuteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::opencogservices::CommandOutput>> PrepareAsyncexecute(::grpc::ClientContext* context, const ::opencogservices::Command& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::opencogservices::CommandOutput>>(PrepareAsyncexecuteRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::opencogservices::CommandOutput>* AsyncexecuteRaw(::grpc::ClientContext* context, const ::opencogservices::Command& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::opencogservices::CommandOutput>* PrepareAsyncexecuteRaw(::grpc::ClientContext* context, const ::opencogservices::Command& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status execute(::grpc::ClientContext* context, const ::opencogservices::Command& request, ::opencogservices::CommandOutput* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::opencogservices::CommandOutput>> Asyncexecute(::grpc::ClientContext* context, const ::opencogservices::Command& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::opencogservices::CommandOutput>>(AsyncexecuteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::opencogservices::CommandOutput>> PrepareAsyncexecute(::grpc::ClientContext* context, const ::opencogservices::Command& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::opencogservices::CommandOutput>>(PrepareAsyncexecuteRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::opencogservices::CommandOutput>* AsyncexecuteRaw(::grpc::ClientContext* context, const ::opencogservices::Command& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::opencogservices::CommandOutput>* PrepareAsyncexecuteRaw(::grpc::ClientContext* context, const ::opencogservices::Command& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_execute_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status execute(::grpc::ServerContext* context, const ::opencogservices::Command* request, ::opencogservices::CommandOutput* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_execute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_execute() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_execute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status execute(::grpc::ServerContext* context, const ::opencogservices::Command* request, ::opencogservices::CommandOutput* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestexecute(::grpc::ServerContext* context, ::opencogservices::Command* request, ::grpc::ServerAsyncResponseWriter< ::opencogservices::CommandOutput>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_execute<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_execute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_execute() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_execute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status execute(::grpc::ServerContext* context, const ::opencogservices::Command* request, ::opencogservices::CommandOutput* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_execute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_execute() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_execute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status execute(::grpc::ServerContext* context, const ::opencogservices::Command* request, ::opencogservices::CommandOutput* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestexecute(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_execute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_execute() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::opencogservices::Command, ::opencogservices::CommandOutput>(std::bind(&WithStreamedUnaryMethod_execute<BaseClass>::Streamedexecute, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_execute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status execute(::grpc::ServerContext* context, const ::opencogservices::Command* request, ::opencogservices::CommandOutput* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedexecute(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::opencogservices::Command,::opencogservices::CommandOutput>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_execute<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_execute<Service > StreamedService;
};

}  // namespace opencogservices


#endif  // GRPC_opencog_2eproto__INCLUDED
