// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opencog.proto

#include "opencog.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace opencogservices {
class CommandOutputDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CommandOutput>
      _instance;
} _CommandOutput_default_instance_;
class CommandDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Command>
      _instance;
} _Command_default_instance_;
}  // namespace opencogservices
namespace protobuf_opencog_2eproto {
static void InitDefaultsCommandOutput() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::opencogservices::_CommandOutput_default_instance_;
    new (ptr) ::opencogservices::CommandOutput();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::opencogservices::CommandOutput::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_CommandOutput =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsCommandOutput}, {}};

static void InitDefaultsCommand() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::opencogservices::_Command_default_instance_;
    new (ptr) ::opencogservices::Command();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::opencogservices::Command::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Command =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsCommand}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_CommandOutput.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Command.base);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::opencogservices::CommandOutput, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::opencogservices::CommandOutput, s_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::opencogservices::Command, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::opencogservices::Command, cmd_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::opencogservices::Command, arg1_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::opencogservices::Command, arg2_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::opencogservices::Command, arg3_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::opencogservices::Command, arg4_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::opencogservices::Command, arg5_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::opencogservices::CommandOutput)},
  { 6, -1, sizeof(::opencogservices::Command)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::opencogservices::_CommandOutput_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::opencogservices::_Command_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "opencog.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\ropencog.proto\022\017opencogservices\"\032\n\rComm"
      "andOutput\022\t\n\001s\030\001 \001(\t\"\\\n\007Command\022\013\n\003cmd\030\001"
      " \001(\t\022\014\n\004arg1\030\002 \001(\t\022\014\n\004arg2\030\003 \001(\t\022\014\n\004arg3"
      "\030\004 \001(\t\022\014\n\004arg4\030\005 \001(\t\022\014\n\004arg5\030\006 \001(\t2Z\n\021Se"
      "rviceDefinition\022E\n\007execute\022\030.opencogserv"
      "ices.Command\032\036.opencogservices.CommandOu"
      "tput\"\000b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 254);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "opencog.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_opencog_2eproto
namespace opencogservices {

// ===================================================================

void CommandOutput::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CommandOutput::kSFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CommandOutput::CommandOutput()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_opencog_2eproto::scc_info_CommandOutput.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:opencogservices.CommandOutput)
}
CommandOutput::CommandOutput(const CommandOutput& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  s_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.s().size() > 0) {
    s_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.s_);
  }
  // @@protoc_insertion_point(copy_constructor:opencogservices.CommandOutput)
}

void CommandOutput::SharedCtor() {
  s_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

CommandOutput::~CommandOutput() {
  // @@protoc_insertion_point(destructor:opencogservices.CommandOutput)
  SharedDtor();
}

void CommandOutput::SharedDtor() {
  s_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void CommandOutput::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* CommandOutput::descriptor() {
  ::protobuf_opencog_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_opencog_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CommandOutput& CommandOutput::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_opencog_2eproto::scc_info_CommandOutput.base);
  return *internal_default_instance();
}


void CommandOutput::Clear() {
// @@protoc_insertion_point(message_clear_start:opencogservices.CommandOutput)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  s_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool CommandOutput::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:opencogservices.CommandOutput)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string s = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_s()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->s().data(), static_cast<int>(this->s().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "opencogservices.CommandOutput.s"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:opencogservices.CommandOutput)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:opencogservices.CommandOutput)
  return false;
#undef DO_
}

void CommandOutput::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:opencogservices.CommandOutput)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string s = 1;
  if (this->s().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->s().data(), static_cast<int>(this->s().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "opencogservices.CommandOutput.s");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->s(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:opencogservices.CommandOutput)
}

::google::protobuf::uint8* CommandOutput::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:opencogservices.CommandOutput)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string s = 1;
  if (this->s().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->s().data(), static_cast<int>(this->s().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "opencogservices.CommandOutput.s");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->s(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:opencogservices.CommandOutput)
  return target;
}

size_t CommandOutput::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:opencogservices.CommandOutput)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string s = 1;
  if (this->s().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->s());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CommandOutput::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:opencogservices.CommandOutput)
  GOOGLE_DCHECK_NE(&from, this);
  const CommandOutput* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CommandOutput>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:opencogservices.CommandOutput)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:opencogservices.CommandOutput)
    MergeFrom(*source);
  }
}

void CommandOutput::MergeFrom(const CommandOutput& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:opencogservices.CommandOutput)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.s().size() > 0) {

    s_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.s_);
  }
}

void CommandOutput::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:opencogservices.CommandOutput)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CommandOutput::CopyFrom(const CommandOutput& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:opencogservices.CommandOutput)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CommandOutput::IsInitialized() const {
  return true;
}

void CommandOutput::Swap(CommandOutput* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CommandOutput::InternalSwap(CommandOutput* other) {
  using std::swap;
  s_.Swap(&other->s_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata CommandOutput::GetMetadata() const {
  protobuf_opencog_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_opencog_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Command::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Command::kCmdFieldNumber;
const int Command::kArg1FieldNumber;
const int Command::kArg2FieldNumber;
const int Command::kArg3FieldNumber;
const int Command::kArg4FieldNumber;
const int Command::kArg5FieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Command::Command()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_opencog_2eproto::scc_info_Command.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:opencogservices.Command)
}
Command::Command(const Command& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  cmd_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.cmd().size() > 0) {
    cmd_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.cmd_);
  }
  arg1_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.arg1().size() > 0) {
    arg1_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.arg1_);
  }
  arg2_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.arg2().size() > 0) {
    arg2_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.arg2_);
  }
  arg3_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.arg3().size() > 0) {
    arg3_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.arg3_);
  }
  arg4_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.arg4().size() > 0) {
    arg4_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.arg4_);
  }
  arg5_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.arg5().size() > 0) {
    arg5_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.arg5_);
  }
  // @@protoc_insertion_point(copy_constructor:opencogservices.Command)
}

void Command::SharedCtor() {
  cmd_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  arg1_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  arg2_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  arg3_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  arg4_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  arg5_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

Command::~Command() {
  // @@protoc_insertion_point(destructor:opencogservices.Command)
  SharedDtor();
}

void Command::SharedDtor() {
  cmd_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  arg1_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  arg2_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  arg3_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  arg4_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  arg5_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Command::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Command::descriptor() {
  ::protobuf_opencog_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_opencog_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Command& Command::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_opencog_2eproto::scc_info_Command.base);
  return *internal_default_instance();
}


void Command::Clear() {
// @@protoc_insertion_point(message_clear_start:opencogservices.Command)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cmd_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  arg1_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  arg2_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  arg3_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  arg4_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  arg5_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool Command::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:opencogservices.Command)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string cmd = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_cmd()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->cmd().data(), static_cast<int>(this->cmd().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "opencogservices.Command.cmd"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string arg1 = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_arg1()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->arg1().data(), static_cast<int>(this->arg1().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "opencogservices.Command.arg1"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string arg2 = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_arg2()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->arg2().data(), static_cast<int>(this->arg2().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "opencogservices.Command.arg2"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string arg3 = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_arg3()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->arg3().data(), static_cast<int>(this->arg3().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "opencogservices.Command.arg3"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string arg4 = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_arg4()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->arg4().data(), static_cast<int>(this->arg4().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "opencogservices.Command.arg4"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string arg5 = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_arg5()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->arg5().data(), static_cast<int>(this->arg5().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "opencogservices.Command.arg5"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:opencogservices.Command)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:opencogservices.Command)
  return false;
#undef DO_
}

void Command::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:opencogservices.Command)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string cmd = 1;
  if (this->cmd().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->cmd().data(), static_cast<int>(this->cmd().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "opencogservices.Command.cmd");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->cmd(), output);
  }

  // string arg1 = 2;
  if (this->arg1().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->arg1().data(), static_cast<int>(this->arg1().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "opencogservices.Command.arg1");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->arg1(), output);
  }

  // string arg2 = 3;
  if (this->arg2().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->arg2().data(), static_cast<int>(this->arg2().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "opencogservices.Command.arg2");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->arg2(), output);
  }

  // string arg3 = 4;
  if (this->arg3().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->arg3().data(), static_cast<int>(this->arg3().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "opencogservices.Command.arg3");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->arg3(), output);
  }

  // string arg4 = 5;
  if (this->arg4().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->arg4().data(), static_cast<int>(this->arg4().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "opencogservices.Command.arg4");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->arg4(), output);
  }

  // string arg5 = 6;
  if (this->arg5().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->arg5().data(), static_cast<int>(this->arg5().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "opencogservices.Command.arg5");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->arg5(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:opencogservices.Command)
}

::google::protobuf::uint8* Command::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:opencogservices.Command)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string cmd = 1;
  if (this->cmd().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->cmd().data(), static_cast<int>(this->cmd().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "opencogservices.Command.cmd");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->cmd(), target);
  }

  // string arg1 = 2;
  if (this->arg1().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->arg1().data(), static_cast<int>(this->arg1().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "opencogservices.Command.arg1");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->arg1(), target);
  }

  // string arg2 = 3;
  if (this->arg2().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->arg2().data(), static_cast<int>(this->arg2().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "opencogservices.Command.arg2");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->arg2(), target);
  }

  // string arg3 = 4;
  if (this->arg3().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->arg3().data(), static_cast<int>(this->arg3().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "opencogservices.Command.arg3");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->arg3(), target);
  }

  // string arg4 = 5;
  if (this->arg4().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->arg4().data(), static_cast<int>(this->arg4().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "opencogservices.Command.arg4");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->arg4(), target);
  }

  // string arg5 = 6;
  if (this->arg5().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->arg5().data(), static_cast<int>(this->arg5().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "opencogservices.Command.arg5");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->arg5(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:opencogservices.Command)
  return target;
}

size_t Command::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:opencogservices.Command)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string cmd = 1;
  if (this->cmd().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->cmd());
  }

  // string arg1 = 2;
  if (this->arg1().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->arg1());
  }

  // string arg2 = 3;
  if (this->arg2().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->arg2());
  }

  // string arg3 = 4;
  if (this->arg3().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->arg3());
  }

  // string arg4 = 5;
  if (this->arg4().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->arg4());
  }

  // string arg5 = 6;
  if (this->arg5().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->arg5());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Command::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:opencogservices.Command)
  GOOGLE_DCHECK_NE(&from, this);
  const Command* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Command>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:opencogservices.Command)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:opencogservices.Command)
    MergeFrom(*source);
  }
}

void Command::MergeFrom(const Command& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:opencogservices.Command)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.cmd().size() > 0) {

    cmd_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.cmd_);
  }
  if (from.arg1().size() > 0) {

    arg1_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.arg1_);
  }
  if (from.arg2().size() > 0) {

    arg2_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.arg2_);
  }
  if (from.arg3().size() > 0) {

    arg3_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.arg3_);
  }
  if (from.arg4().size() > 0) {

    arg4_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.arg4_);
  }
  if (from.arg5().size() > 0) {

    arg5_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.arg5_);
  }
}

void Command::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:opencogservices.Command)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Command::CopyFrom(const Command& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:opencogservices.Command)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Command::IsInitialized() const {
  return true;
}

void Command::Swap(Command* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Command::InternalSwap(Command* other) {
  using std::swap;
  cmd_.Swap(&other->cmd_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  arg1_.Swap(&other->arg1_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  arg2_.Swap(&other->arg2_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  arg3_.Swap(&other->arg3_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  arg4_.Swap(&other->arg4_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  arg5_.Swap(&other->arg5_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Command::GetMetadata() const {
  protobuf_opencog_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_opencog_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace opencogservices
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::opencogservices::CommandOutput* Arena::CreateMaybeMessage< ::opencogservices::CommandOutput >(Arena* arena) {
  return Arena::CreateInternal< ::opencogservices::CommandOutput >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::opencogservices::Command* Arena::CreateMaybeMessage< ::opencogservices::Command >(Arena* arena) {
  return Arena::CreateInternal< ::opencogservices::Command >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
